name: Build the BikeComputer application
on:
  pull_request:
  push:

jobs:
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [DISCO_H747I]
        profile: [debug]
            

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
              
      -
        name: build
        run: |
          set -e
          mbed deploy
          mbed test -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }} --compile -n tests-simple-test-always-succeed
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
